### ISSUE TITLE
not work in Safari

### ISSUE THREAD

**Issue by KaroseLiu** [rehooks/local-storage#22] opened 2019-06-25 10:48 UTC
Safari not listen the change 

codeSandboxlink: https://codesandbox.io/s/adoring-wright-y7cw2

**Comment by jharrilim** [comment] 2019-06-25 10:53
Seems like we will need to polyfill for Safari and IE.

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill

**Comment by firzanarmani** [comment] 2019-07-17 06:28
Anyone had any success with this?

**Comment by jharrilim** [comment] 2019-07-17 11:09
I would try including the polyfill in the beginning of your code.

Perhaps use this implementation:
https://www.npmjs.com/package/custom-event-polyfill

I realized it might be a bit odd for us to stick it in our implementation, as we are just creating a react hook, as opposed to creating a react hook and polyfilling CustomEvent. Adding that global object might be a side effect you would want explicit control over.

**Comment by ekrokowski** [comment] 2019-08-27 18:05
@firzanarmani @jharrilim Even with `custom-event-polyfill` it doesn't seem to work:

https://codesandbox.io/s/cranky-shadow-bbo2r

**Comment by jharrilim** [comment] 2019-08-31 20:15
Unfortunately I'm not of much use for helping with this testing... I don't have a Mac. Does it show any error in the console?

**Comment by gmdayley** [comment] 2019-09-26 20:07
The issue is that the check  `event instanceof LocalStorageChanged` doesn't work in Safari.   If instead you check the type `event.type === LocalStorageChanged.eventName`  it will work.  I'll try to submit a PR if I get a chance.

**Comment by lookfirst** [comment] 2019-10-01 04:18
fixed in pr #25

**Closed** 2019-11-08 04:32 UTC
Labels: bug
